### PR TITLE
add 'linkerArgs' config option

### PR DESCRIPTION
**Pull request by kristofdho**
In combination with https://github.com/gluonhq/substrate/pull/1103, this fixes https://github.com/gluonhq/substrate/issues/1101

### CODE REVIEW

**Comment by jperedadnr** [comment]
@kristofdho Can you create the same PR for the GluonFX gradle plugin? https://github.com/gluonhq/gluonfx-gradle-plugin

**Review by jperedadnr — APPROVED** [review]
Looks good.
We'll add it to the documents too https://docs.gluonhq.com/#_configuration

**Review by johanvos — APPROVED** [review]

**Comment by kristofdho** [comment]
Any idea when a new release is scheduled? Just so we can plan this in accordingly.

**Comment by adam-sandor** [comment]
Hi, I'm getting the dreaded `java.lang.UnsatisfiedLinkError: no awt in java.library.path` error because I'm using some AWT image manipulation stuff to process PDF docs. As I understand this option was added so address that problem (at least all paths lead to this PR). Unfortunately with my level of knowledge about GraalVM I have no idea how to use this configuration to make sure AWT is available to the final executable. Can you help me out here? Thanks!

**Pull request merged**
